spring.application.name=user-service

server.port=8081

# Cassandra local development configuration
spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.keyspace-name=user_service
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=create_if_not_exists

app.cassandra.replication-factor=1
